# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
