# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0005_auto_20160215_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='photo',
            field=models.ImageField(blank=True, upload_to='person-photo'),
        ),
    ]
