# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 16:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0007_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_person', models.CharField(max_length=100)),
                ('comment_time', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.CharField(blank=True, max_length=430)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.Post')),
            ],
        ),
    ]
